name: food_fight
description: "Food Fight - Food Delivery App (Customer Panel - Frontend Only)"
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.1.0
  google_sign_in: ^6.2.2
  # Supabase
  supabase_flutter: ^2.17.2
  # Storage
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  uuid: ^4.5.0
  path: ^1.9.0
  # Utils
  dio: ^5.7.0
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/branding/

flutter_launcher_icons:
  android: true
  image_path: "assets/images/branding/food_fight_logo_icon.png"
  adaptive_icon_background: "#FFD504"
  adaptive_icon_foreground: "assets/images/branding/food_fight_logo_icon.png"
