// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBesdyc6ixO-A3pLzLJInPpquKlHsqp42Q',
    appId: '1:585587375994:web:26b1a17cfd2e6f7708a0c3',
    messagingSenderId: '585587375994',
    projectId: 'food-fight-bd72e',
    authDomain: 'food-fight-bd72e.firebaseapp.com',
    storageBucket: 'food-fight-bd72e.firebasestorage.app',
    measurementId: 'G-E4GSKJE3M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQvloEItg5cCuZpWBaBK73bM6YIvMhwSc',
    appId: '1:585587375994:android:35a98cfa7fc579f208a0c3',
    messagingSenderId: '585587375994',
    projectId: 'food-fight-bd72e',
    storageBucket: 'food-fight-bd72e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiKzs7mWS7JoU8bF1GEGdjkCAvm_6jSpg',
    appId: '1:585587375994:ios:367fcc3fd172478008a0c3',
    messagingSenderId: '585587375994',
    projectId: 'food-fight-bd72e',
    storageBucket: 'food-fight-bd72e.firebasestorage.app',
    iosClientId: '585587375994-5ak89r759o150jh93cubkp5o92b9l6q3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodFight',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiKzs7mWS7JoU8bF1GEGdjkCAvm_6jSpg',
    appId: '1:585587375994:ios:367fcc3fd172478008a0c3',
    messagingSenderId: '585587375994',
    projectId: 'food-fight-bd72e',
    storageBucket: 'food-fight-bd72e.firebasestorage.app',
    iosClientId: '585587375994-5ak89r759o150jh93cubkp5o92b9l6q3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodFight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBesdyc6ixO-A3pLzLJInPpquKlHsqp42Q',
    appId: '1:585587375994:web:4d16a76584886a6e08a0c3',
    messagingSenderId: '585587375994',
    projectId: 'food-fight-bd72e',
    authDomain: 'food-fight-bd72e.firebaseapp.com',
    storageBucket: 'food-fight-bd72e.firebasestorage.app',
    measurementId: 'G-97900QYK9B',
  );
}
